/* ============================================================================
   THE STORY NIGHT — flipbook behaviour.
   Diagnostic first: surface any REAL JavaScript error on screen (a silent error
   would stop the click handlers from ever attaching). Image / video / network
   load failures are ignored — they have no .message and are handled per-element.
   ============================================================================ */
window.addEventListener("error", function (ev) {
  if (!ev || !ev.message) return;                 // ignore resource-load errors
  var b = document.getElementById("__jsErr");
  if (!b) {
    b = document.createElement("div");
    b.id = "__jsErr";
    b.style.cssText = "position:fixed;left:0;right:0;bottom:0;z-index:100000;" +
      "background:#b00020;color:#fff;font:13px/1.5 monospace;padding:10px;white-space:pre-wrap";
    (document.body || document.documentElement).appendChild(b);
  }
  b.textContent = "⚠ JavaScript error (this is likely why the book won't open):\n" +
    ev.message + "\n" + (ev.filename || "") + " : line " + ev.lineno;
});

// If you can read this line in the console, the script parsed with NO syntax
// error and you are running the CURRENT file (not a cached copy).
console.log("%c✅ [The Story Night] loaded — 3D flipbook · full-bleed pages · speech bubbles.",
            "font-weight:bold;color:#7d5fd0;font-size:13px");

/* ============================================================================
   ██  EDIT YOUR CONTENT HERE  ██
   ----------------------------------------------------------------------------
   Every entry below is ONE page of the book, shown in order after the cover.

     • type   : "video"  → a full-page video (WebM/VP9, e.g. assets/1.webm)
                "image"  → a full-page picture (WebP, e.g. assets/3.webp)
                "lbd"    → an embedded game page (see the LBD OVERLAY section)
                "end"    → THE END page
     • src    : the media file for that page (for "lbd", the game's index.html).
     • poster : (video only) that clip's frame-0 WebP, so the page paints instantly.
     • interactive : (optional) true when the page owns a required learner activity;
                the forward gate then also waits for Flipbook.markInteractionComplete().
                Every "lbd" page is treated as interactive whether or not the flag is
                written here — finishing the game IS that page's activity.
     • delay  : (video only, optional) milliseconds to wait after landing on the
                page before the video starts (e.g. delay: 3000 → starts after 3s).
                Omit / 0 → the video starts instantly.
     • bubble : (optional) a speech bubble that POPS IN once the reader has
                FULLY landed on the page. Set:
                   kind     : "neel" (pink) or "everywhere" (glowing) — picks
                              which bubble artwork + crop to use.
                   text     : the words shown inside the bubble.
                   box      : where + how big — { top/left/right/bottom, w }.
                              positions are CSS lengths (e.g. "3%"); w is the
                              bubble WIDTH in book-space px (book is 1280x720).
                   flip     : true → mirror the bubble so its tail points the
                              other way.
                   textLeft / textTop / fontSize : fine-tune the words inside.

   Add / remove / reorder pages freely — the flip engine and the "Page X / N"
   counter update automatically.
   ============================================================================ */
// Each video page names its own first-frame POSTER explicitly (no path-munging
// regex) so the scene paints instantly instead of showing a blank dark-blue page
// while the clip buffers — and because the poster IS frame 0 of that clip, there is
// no visual jump when playback starts. Posters are generated by
// tools/convert-media.js into assets/posters/.
//
// MEDIA FORMATS: videos are WebM (VP9 video + Opus audio) and images are WebP —
// supported by Chrome, Edge, Firefox and Safari 15+ (macOS 12+ / iOS 15+).
//
// `interactive: true` marks a page that owns a required learner activity; the
// forward gate then waits for BOTH the video and that activity (see the FIRST-PAGE
// GATE section). Video pages with no activity only wait for the video. The game
// pages carry it because finishing the game is the ONLY way forward from them —
// their Next arrow stays absent until the game reports completion.
const pages = [
  { type: "video", src: "assets/1.webm", poster: "assets/posters/1.webp" },   // 1 — opening video
  { type: "video", src: "assets/2.webm", poster: "assets/posters/2.webp" },   // 2
  { type: "video", src: "assets/3.webm", poster: "assets/posters/3.webp" },   // 3
  // 4 — EMBEDDED GAME 1 (immediately after story page 3): "Byte's Energy Hunt".
  // The leaf shows the game's intro artwork as a poster; the live game is the
  // body-level overlay iframe, revealed over this page's content frame when you land
  // here and expanded to fullscreen only once the learner taps Play inside it.
  // Finishing it posts lbd-complete → the overlay shrinks back and the page turns.
  // poster = the game's own INTRO artwork (assets/start.webp), not the bare farm field —
  // so the page turn lands on exactly the image the warmed iframe then shows, and the
  // first game screen reads as printed on the page instead of swapping art on arrival.
  { type: "lbd", src: "LBD%201/index.html", poster: "LBD%201/assets/start.webp", interactive: true },
  { type: "video", src: "assets/4.webm", poster: "assets/posters/4.webp" },   // 5 — story page 4
  // 6 — EMBEDDED GAME 2 (immediately after story page 4): "Right & Left".
  { type: "lbd", src: "LBD%202/Right-and-Left/index.html", poster: "LBD%202/Right-and-Left/Assets/UI/start-screen.webp", interactive: true },
  { type: "end" },                           // 7 — THE END page (cream) + Replay
];

/* ============================================================================
   ██  END OF EDITABLE CONTENT — engine below (no need to change) ██
   ============================================================================ */

/* ---- Build one page face's media (image OR video OR lbd poster) ---------- */
function makeMedia(page) {
  // "lbd" pages show a STILL poster on the leaf itself (seen while the page turns);
  // the live, interactive game is a separate full-screen-capable overlay iframe
  // (see the LBD OVERLAY section below) — it can't live inside the 3D-transformed
  // leaf because CSS transforms trap position:fixed, so true fullscreen would fail.
  if (page.type === "lbd") {
    const img = document.createElement("img");
    img.className = "page-media";
    img.draggable = false;
    img.addEventListener("dragstart", function (e) { e.preventDefault(); });
    img.decoding = "async";
    img.src = page.poster || "";
    img.alt = "Stairway Shuffle — tap Start to play";
    return img;
  }
  const media = page.type === "video"
    ? document.createElement("video")
    : document.createElement("img");
  media.className = "page-media";
  media.draggable = false;                           // never let the image "ghost-drag" out
  media.addEventListener("dragstart", function (e) { e.preventDefault(); });
  media.src = page.src;
  if (page.type === "video") {
    media.loop = false;
    media.playsInline = true;
    media.setAttribute("playsinline", "");            // iOS Safari inline playback
    media.setAttribute("webkit-playsinline", "");
    // FIRST-FRAME POSTER: the page surface (--paper) is deep night-blue, so a video
    // that hasn't painted a frame yet (still buffering, or autoplay was blocked) would
    // show as a BLANK dark-blue page. The poster is that clip's own frame 0, so the
    // scene shows INSTANTLY and — because it equals where playback starts — there's no
    // jump when the video then plays. Taken straight from the page config: no path
    // rewriting, so changing a media format can't silently break the poster.
    if (page.poster) media.setAttribute("poster", page.poster);
    // LAZY: do NOT eager-buffer. With 25 videos, preload="auto" made the browser
    // open + decode every clip on load (huge memory/CPU spike + open lag). We only
    // buffer the page you're on + the next one, on demand (see warmVideo()).
    media.preload = "none";
    // Tap the video to (re)start it WITH sound — a guaranteed user gesture, so
    // browsers that blocked the auto-start's audio will now allow it.
    media.addEventListener("click", function () {
      media.muted = false;
      try { if (media.ended) media.currentTime = 0; } catch (_) {}
      const p = media.play(); if (p && p.catch) p.catch(function () {});
    });
    // The "turn the page" GLOW CUE on the forward arrow is NOT fired from here.
    // This `ended` listener and the forward gate's own `ended` listener race, so the
    // arrow can still be hidden/disabled at this instant; pulseNextArrow() is fired
    // from releaseVideoGate() instead — i.e. the moment the arrow actually becomes
    // available — and guards itself against animating an invisible button.
    media.addEventListener("ended", function () {
      if (!opened || !ready || lbdFullscreen || flipped >= totalPages - 1) return;
      if (!leaves[flipped] || !leaves[flipped].contains(media)) return;   // only the current page
      // FLIP-PAGE TUTORIAL: once THIS page's video finishes, wait 5s then run the
      // page-turn guidance (hand swipe + ghost page-flip + blinking arrow), which
      // repeats until the reader turns the page. Any interaction cancels it.
      scheduleVideoEndTutorial();
    });
  } else {
    media.decoding = "async";
    media.alt = page.alt || "story page";
  }
  return media;
}

/* ---- Build one speech bubble (hidden until the page fully lands) ---------
   The bubble artwork + crop live in styles.css (.bubble.neel / .bubble.everywhere).
   Here we only apply the per-page geometry (position, width, flip) + the text. */
function makeBubble(bubble) {
  const wrap = document.createElement("div");
  wrap.className = "bubble" + (bubble.kind ? " " + bubble.kind : "");

  const box = bubble.box || {};
  ["top", "left", "right", "bottom"].forEach(function (k) {
    if (box[k] != null) wrap.style[k] = box[k];
  });
  if (box.w != null) wrap.style.setProperty("--w", box.w + "px");

  const bg = document.createElement("div");
  bg.className = "bubble-bg" + (bubble.flip ? " flip" : "");
  wrap.appendChild(bg);

  if (bubble.text) {
    const t = document.createElement("div");
    t.className = "bubble-text";
    t.textContent = bubble.text;
    if (bubble.textLeft) t.style.left = bubble.textLeft;
    if (bubble.textTop)  t.style.top  = bubble.textTop;
    if (bubble.fontSize) t.style.fontSize = bubble.fontSize;
    wrap.appendChild(t);
  }
  return wrap;
}

/* ---- Build one SVG speech bubble (white + black outline + purple glow) -----
   cfg = { text, box:{top,left,right,bottom,w}, tail, rot, fontSize }
     box   : position of the bubble box + its WIDTH in book-space px
     tail  : "down" | "down-left" | "down-right"  (which way the tail points)
     rot   : tilt in degrees (optional)
   Hidden until the page lands (revealed by refreshMedia). */
const SBUB_TAILS = {
  "down":       "M42 57 L58 57 L50 73 Z",
  "down-left":  "M30 55 L47 59 L16 73 Z",
  "down-right": "M53 59 L70 55 L84 73 Z"
};
function makeSpeechBubble(cfg) {
  const wrap = document.createElement("div");
  wrap.className = "sbub";
  const box = cfg.box || {};
  ["top", "left", "right", "bottom"].forEach(function (k) {
    if (box[k] != null) wrap.style[k] = box[k];
  });
  if (box.w != null) wrap.style.setProperty("--sbw", box.w + "px");
  if (cfg.rot)       wrap.style.setProperty("--sbrot", cfg.rot + "deg");

  const tailPath = SBUB_TAILS[cfg.tail] || SBUB_TAILS.down;
  wrap.innerHTML =
    '<svg class="sbub-svg" viewBox="0 0 100 74" aria-hidden="true">' +
      '<g class="sbub-shape">' +
        '<path d="' + tailPath + '"/>' +
        '<ellipse cx="50" cy="32" rx="47" ry="29"/>' +
      '</g>' +
    '</svg>';

  const t = document.createElement("div");
  t.className = "sbub-text";
  t.textContent = cfg.text || "";
  if (cfg.fontSize) t.style.fontSize = cfg.fontSize + "px";
  wrap.appendChild(t);
  return wrap;
}

/* ---- Build the pages (one CSS 3D "leaf" per entry) ---------------------- */
const flipbookEl  = document.getElementById("flipbook");
const pageStackEl = flipbookEl ? flipbookEl.querySelector(".page-stack") : null;   // right-side page stack
const flipScaleEl = document.getElementById("flipScale");
const coverScene  = document.getElementById("coverScene");
// ONE full 16:9 page per view (single display). page 1 = entry 1. The themed
// book frame forms the left spine/cover edge (always visible when open); pages
// flip normally. No two-page spread.
const totalPages = pages.length;
// Embedded games: there can be MORE THAN ONE lbd page. One overlay iframe is reused
// for whichever game page you're on (only one is ever shown at a time). LBD_INDEX
// stays as a simple "is there any game at all?" flag (-1 = none); isLbdPage(i) tests
// a specific leaf.
const LBD_INDEX = pages.findIndex(function (p) { return p.type === "lbd"; });
function isLbdPage(i) { return !!(pages[i] && pages[i].type === "lbd"); }

// Each leaf is a full 16:9 page hinged on the LEFT spine:
//   • FRONT = the page's full-bleed image / video (+ its speech bubble, if any).
//   • BACK  = a BLANK parchment sheet (seen edge-on while the page turns).
const leaves = [];
pages.forEach(function (page, i) {
  const leaf = document.createElement("div");
  leaf.className = "leaf";

  const front = document.createElement("div");
  front.className = "face front";
  if (page.type === "end") {
    // THE END — a real final page (cream "paper") with a gold-plum title + Replay.
    front.classList.add("end-page");
    front.innerHTML =
      '<div class="end-page-inner">' +
        '<div class="end-title">THE&nbsp;END</div>' +
        '<button class="replay-btn" id="replayBtn" type="button" aria-label="Replay from the beginning">' +
          '<svg viewBox="0 0 24 24" aria-hidden="true">' +
            '<path d="M12 5V1L7 6l5 5V7c3.31 0 6 2.69 6 6s-2.69 6-6 6-6-2.69-6-6H4c0 4.42 3.58 8 8 8s8-3.58 8-8-3.58-8-8-8z"/>' +
          '</svg>' +
          '<span>Replay</span>' +
        '</button>' +
      '</div>';
  } else {
    front.appendChild(makeMedia(page));                       // full-bleed image / video
    if (page.bubble) front.appendChild(makeBubble(page.bubble));  // PNG speech bubble (revealed on land)
  }
  const curl = document.createElement("div");               // moving page-curl shading
  curl.className = "curl";
  front.appendChild(curl);

  const back = document.createElement("div");
  back.className = "face back";                             // blank reverse side (no content)

  leaf.appendChild(front);
  leaf.appendChild(back);
  flipbookEl.appendChild(leaf);
  leaves.push(leaf);
});

/* ---- State + element references ----------------------------------------- */
const bookStage  = document.getElementById("bookStage");
const book       = document.getElementById("book");
const bookPop    = document.getElementById("bookPop");
const bookFloat  = document.getElementById("bookFloat");
const cover      = document.getElementById("cover");
const hint       = document.getElementById("hint");
/* The corner arrows are the ONE set of prev/next controls (the #prev/#next circles
   and the Home button were removed along with their dead refs). */
const cornerPrev  = document.getElementById("cornerPrev");
const cornerNext  = document.getElementById("cornerNext");
const replayBtn   = document.getElementById("replayBtn");   // lives on the THE END page (built above)

/* ==========================================================================
   LBD OVERLAY  —  the two embedded games, each shown as one page.
   The game lives in a body-level iframe (#lbdOverlay) so it can grow to true
   fullscreen (a transform on .flip-scale would otherwise trap position:fixed).
   • pre-LBD  : the overlay is sized/positioned OVER the current page rectangle,
                so the game's home screen looks like it's printed inside the book.
   • start    : the game posts {source:"lbd", type:"lbd-start"} → we expand the
                overlay to fill the whole screen.
   • end/skip : the game posts {source:"lbd", type:"lbd-complete"} → we shrink the
                overlay back into the page and auto-flip to the next page.
   ========================================================================== */
const lbdOverlay = document.getElementById("lbdOverlay");
const lbdFrame   = document.getElementById("lbdFrame");
let lbdFullscreen = false;   // is the overlay expanded to true fullscreen right now?
let lbdStarted    = false;   // has the learner tapped Play inside the game this visit?
let lbdWasOn      = false;   // was the overlay showing on the previous refresh?
let lbdExiting    = false;   // guard so "complete" only advances once
let lbdReadySrc   = "";      // which game src has reported lbd-ready
let lbdRevealTimer = null;   // fallback so a missing lbd-ready never stalls the reveal
const LBD_ANIM_MS = 400;     // keep in sync with .lbd-stage.lbd-anim in styles.css

// A neutral dark backdrop shows inside the frame while a game loads / is unloaded so
// there's no flash; the target game's own intro poster is layered behind it so its
// home screen fades in seamlessly.
if (lbdFrame) lbdFrame.style.background = "#0a0f2d";

/* Which game should be warm right now? The next game page at or after the current
   position — one iframe serves both games, and the learner can only ever be
   approaching one of them. Past the last game, keep the last one (harmless). */
function nextLbdIndex() {
  for (let i = Math.max(0, flipped); i < pages.length; i++) if (isLbdPage(i)) return i;
  for (let i = pages.length - 1; i >= 0; i--) if (isLbdPage(i)) return i;
  return -1;
}

/* Boot a game into the iframe. Both games are SILENT until their own Play button is
   tapped (verified: every sound in either build is behind that gesture), so it is
   safe to boot one hidden and leave it sitting on its intro screen. */
function loadLbd(idx) {
  const p = pages[idx];
  if (!lbdFrame || !p || p.type !== "lbd") return;
  if (lbdFrame.dataset.loaded === p.src) return;      // already the live game
  if (p.poster) lbdFrame.style.background = "#0a0f2d url('" + p.poster + "') center/cover no-repeat";
  lbdReadySrc = "";
  lbdFrame.dataset.loaded = p.src;
  lbdFrame.src = p.src;
}

/* STAGE B, iframe half: warm the upcoming game during idle time AFTER window.load,
   so it is booted and sitting on its intro long before the learner arrives — that is
   what makes the reveal instant with no spinner and no second loading screen.
   Never called on the critical path to the Start button. */
const idleCb = window.requestIdleCallback
  ? function (fn) { return window.requestIdleCallback(fn, { timeout: 2000 }); }
  : function (fn) { return setTimeout(fn, 200); };   // Safari / no idle callback

function warmLbd() {
  if (!lbdFrame || lbdFullscreen) return;            // never disturb a live game
  const idx = nextLbdIndex();
  if (idx < 0) return;
  idleCb(function () {
    if (lbdFullscreen) return;
    if (isLbdPage(flipped) && flipped !== idx) return;   // don't swap out the game we're on
    loadLbd(idx);
  });
}

/* Unload the game: kills every remaining timer, animation frame, audio element and
   video decode inside it in one step, and guarantees the next visit starts from a
   fresh intro rather than a half-played level. */
function resetLbd() {
  if (!lbdFrame) return;
  lbdStarted = false;
  lbdReadySrc = "";
  lbdFrame.dataset.loaded = "";
  lbdFrame.src = "about:blank";
}

/* Tear down, then silently re-warm from cache so revisiting the page is instant.
   Every asset is already in the HTTP cache by now, so the reboot costs no network. */
function resetAndRewarmLbd() {
  resetLbd();
  idleCb(warmLbd);
}

/* Park the overlay exactly over the on-screen page rectangle — the game's intro then
   looks like it is printed inside the book. */
function positionLbdOverlay() {
  if (!lbdOverlay) return;
  const r = flipScaleEl.getBoundingClientRect();   // the scaled 1280×720 content frame
  lbdOverlay.style.left   = r.left   + "px";
  lbdOverlay.style.top    = r.top    + "px";
  lbdOverlay.style.width  = r.width  + "px";
  lbdOverlay.style.height = r.height + "px";
}

let lbdAnimTimer = null;
function setLbdFullscreen(on) {
  if (!lbdOverlay) return;
  if (lbdFullscreen === on) return;                 // no re-entry: never reload mid-expand
  lbdFullscreen = on;
  positionLbdOverlay();                             // make the page-rect geometry current
  lbdOverlay.classList.add("lbd-anim");             // enable the box-morph for this toggle only
  void lbdOverlay.offsetWidth;                      // commit, so the change below animates from here
  lbdOverlay.classList.toggle("lbd-is-fullscreen", on);
  document.body.classList.toggle("lbd-fullscreen", on);
  clearTimeout(lbdAnimTimer);
  lbdAnimTimer = setTimeout(function () { lbdOverlay.classList.remove("lbd-anim"); }, LBD_ANIM_MS + 60);
  // The game plays its own theme while it's up; pause the flipbook's 20% bed so the
  // same track doesn't double up, and bring it back on the way out.
  try {
    if (on) { bgMusic.pause(); }
    // Only resume on the way OUT if we're staying in the book. Home / Replay tear the
    // overlay down as part of closing, and restarting the music for the ~2s of the
    // closing swing (before resetToStart pauses it again) is an audible blip.
    else if (opened && !document.body.classList.contains("is-closing")) { playBgMusic(); }
  } catch (_) {}
  // Suppress the idle page-turn guidance for as long as the game owns the screen.
  if (on) { hideFlipHint(); clearTimeout(idleHintTimer); clearTimeout(nudgeHideTimer); clearTimeout(videoEndHintTimer); }
}

/* Reveal the (already warmed) overlay over the game page's content frame. No
   fullscreen yet — the learner interacts with the game's intro inside the book, and
   only tapping Play expands it. */
function revealLbdOverlay() {
  if (!lbdOverlay) return;
  positionLbdOverlay();
  lbdOverlay.classList.add("visible");
  lbdOverlay.setAttribute("aria-hidden", "false");
}

function hideLbdOverlay() {
  if (!lbdOverlay) return;
  lbdOverlay.classList.remove("visible");
  lbdOverlay.setAttribute("aria-hidden", "true");
}

/* Show / hide the overlay as the learner arrives at and leaves a game page. */
function updateLbdOverlay() {
  if (LBD_INDEX < 0 || !lbdOverlay) return;
  const onLbd = opened && ready && !animating && isLbdPage(flipped);
  clearTimeout(lbdRevealTimer);

  if (onLbd) {
    loadLbd(flipped);                    // normally a no-op: warm-up booted it already
    lbdWasOn = true;
    // Suppress the idle page-turn hints on this page (canShowHint() also refuses).
    hideFlipHint(); clearTimeout(idleHintTimer); clearTimeout(videoEndHintTimer);
    if (lbdReadySrc === pages[flipped].src) {
      revealLbdOverlay();                // warmed and ready → reveal immediately
    } else {
      // Not ready yet (a cold first visit, or the warm-up hasn't run): wait briefly
      // for lbd-ready, but reveal regardless after a short fallback so a game that
      // never reports ready can't leave the learner staring at a blank page.
      lbdRevealTimer = setTimeout(function () {
        if (isLbdPage(flipped)) revealLbdOverlay();
      }, 600);
    }
  } else if (!lbdFullscreen) {           // never hide mid-game
    hideLbdOverlay();
    if (lbdWasOn) {
      lbdWasOn = false;
      // Left the page (with or without starting): kill the game's audio and timers
      // outright, then silently re-warm so coming back is instant and fresh.
      resetAndRewarmLbd();
    }
  }
}

/* Completion: shrink the game back into the page frame, then turn to the next story
   page, tear the iframe down and re-warm. */
function exitLbd() {
  if (lbdExiting) return;
  lbdExiting = true;
  // The game is finished: satisfy this page's activity requirement NOW, while `flipped`
  // still points at the game page. That opens its gate for good (clearedPages), so
  // paging back to the game later shows a live Next arrow instead of trapping the
  // learner into replaying it. No glow pulse: we are about to auto-advance anyway, and
  // a 400ms flash on an arrow nobody was waiting for is just noise.
  armNextPulse = false;
  markInteractionComplete(flipped);
  // Stop accepting game input for the whole closing transition.
  if (lbdOverlay) lbdOverlay.style.pointerEvents = "none";
  setLbdFullscreen(false);                    // animate back into the page rectangle
  setTimeout(function () {
    hideLbdOverlay();
    lbdWasOn = false;                         // we tear down here, so don't do it twice
    const wasOn = isLbdPage(flipped);
    resetAndRewarmLbd();                      // kill all media/timers, then re-warm
    if (lbdOverlay) lbdOverlay.style.pointerEvents = "";
    lbdExiting = false;
    if (wasOn) goNext(true);                  // auto-advance past the game page
  }, LBD_ANIM_MS + 70);                       // just after the shrink transition
}

/* Any exit that ISN'T a completion (Home, Replay, Reset): drop fullscreen, hide the
   overlay, kill the game, and clear every stale class. */
function teardownLbd() {
  clearTimeout(lbdRevealTimer);
  if (lbdFullscreen) setLbdFullscreen(false);
  lbdFullscreen = false;
  if (lbdOverlay) {
    lbdOverlay.classList.remove("lbd-is-fullscreen", "lbd-anim");
    lbdOverlay.style.pointerEvents = "";
  }
  document.body.classList.remove("lbd-fullscreen");
  hideLbdOverlay();
  lbdWasOn = false;
  lbdExiting = false;
  resetAndRewarmLbd();
}

/* Messages from the game. Validated twice, as required: the event must come from the
   live iframe's own window AND carry our source tag. */
window.addEventListener("message", function (e) {
  const d = e && e.data;
  if (!d || d.source !== "lbd") return;
  if (!lbdFrame || e.source !== lbdFrame.contentWindow) return;
  if (d.type === "lbd-ready") {
    lbdReadySrc = lbdFrame.dataset.loaded || "";
    // Already standing on the page waiting for this? Reveal now.
    if (isLbdPage(flipped) && lbdWasOn && pages[flipped].src === lbdReadySrc) {
      clearTimeout(lbdRevealTimer);
      revealLbdOverlay();
    }
  } else if (d.type === "lbd-start") {
    if (!isLbdPage(flipped)) return;          // only the game we're actually on
    lbdStarted = true;
    setLbdFullscreen(true);
  } else if (d.type === "lbd-complete") {
    if (!isLbdPage(flipped)) return;
    exitLbd();
  }
});

/* FULLSCREEN WATCHDOG — the lbd-start message above is the fast path, but a RUNNING
   game boxed inside the page frame must be impossible even if that one message is
   ever lost or mistimed (posted mid page-turn while `flipped` still pointed at the
   old page, swallowed by the bridge's once-per-start guard, etc.). The game iframe
   is same-origin, so the parent can read the definitive start signal directly: both
   games hide their #startScreen (class "hide") the moment real play begins. While
   the learner is on a game page with the overlay up but not fullscreen, poll that
   signal and expand the moment it's true. Idle cost is one classList read every
   400ms only while a game page is showing; every other state exits on the guards. */
setInterval(function () {
  if (!lbdOverlay || !lbdFrame) return;
  if (lbdFullscreen || lbdExiting) return;               // already expanded / closing down
  if (!isLbdPage(flipped)) return;                        // not on a game page
  if (!lbdOverlay.classList.contains("visible")) return;  // game not shown yet
  if (lbdFrame.dataset.loaded !== pages[flipped].src) return; // iframe holds another game
  try {
    const doc = lbdFrame.contentDocument;
    const ss = doc && doc.getElementById("startScreen");
    if (ss && ss.classList.contains("hide")) {            // game is genuinely running
      lbdStarted = true;
      setLbdFullscreen(true);
    }
  } catch (_) { /* cross-origin deployment → the postMessage path alone applies */ }
}, 400);

let opened = false;      // has the cover been opened?
let ready  = false;      // has the cover FINISHED opening? (flips allowed only then)
let flipped = 0;         // how many leaves are currently turned to the left
let animating = false;   // guard so a new turn can't start mid-flip
const FLIP_MS = 1150;    // keep in sync with --flip-ms in styles.css
const COVER_OPEN_MS = 6000;  // keep in sync with the coverOpen animation in styles.css
const CLOSE_SETTLE_MS = 560;  // keep in sync with the bookSettle animation in styles.css
const COVER_CLOSE_MS  = 2000; // Home/Replay: cover swings shut (reverse open); sync with coverClose in styles.css
let _openTimer = null;   // pending "cover finished opening" timer
let _homeTimer = null;   // pending "cover finished closing → back to the cover" timer

/* ---- Responsive: scale the FIXED 1280x720 book to fit the viewport --------
   The book stays internally 1280x720 and is ONLY transform-scaled, so turn.js's
   paper-curl maths is never distorted. This function does two jobs, in order:

     1. RESERVE A REAL GUTTER. The controls are sized by --nav-btn in CSS; we subtract
        the FULL control band (edge inset + button + gap) from the available height
        BEFORE solving for the scale, so the book shrinks to make room for the
        controls and never the other way round.
     2. PUBLISH THE BOOK'S GEOMETRY on :root, so CSS can position the controls against
        the BOOK's edges instead of the viewport's. Those were two independent
        coordinate systems, which is exactly what let the buttons drift onto the book
        (and off the screen) on every viewport that wasn't 16:9. */

/* .book-frame outsets the 1280x720 page area — styles.css has
   `inset: -16px -42px -16px -16px` — so the book's TRUE visible box is bigger than
   .flip-scale, and ASYMMETRIC: 42px on the right, 16px on the other three sides, in
   BOOK space (i.e. these scale with the book). The old fit treated the outset as a
   symmetric 42px and left it out of the height solve entirely. */
const FRAME_T = 16, FRAME_R = 42, FRAME_B = 16, FRAME_L = 16;
/* Floor of --nav-edge-y in styles.css. JS cannot evaluate env(), so this mirrors only
   the floor; a larger real safe-area inset makes CSS keep the button on-screen, which
   the `min()` in .corner-arrow handles (see the note there). */
const NAV_EDGE = 10;
/* Breathing room on each side, matching the original 0.88-of-width fit. */
const SIDE_MARGIN = 0.06;

/* MUST stay in lockstep with --nav-btn in styles.css. A clamp()/min() chain cannot be
   read back out of getComputedStyle (it returns the unevaluated token stream), so the
   single token is mirrored here — and tests/nav-layout.spec.js asserts the two agree.
   clamp(MIN, V, MAX) === max(MIN, min(V, MAX)). */
function navBtnPx() {
  const w = window.innerWidth, h = window.innerHeight;
  return Math.max(56, Math.min(0.08 * Math.min(w, h), 0.22 * h, 0.30 * w, 112));
}

function fitScale() {
  const vw = window.innerWidth, vh = window.innerHeight;
  const nav = navBtnPx();
  const gap = nav * 0.35;                            // --nav-gap
  // The band the controls own. Reserved on BOTH the top and the bottom so the book
  // stays vertically CENTRED (only the bottom band is occupied now that Home is gone;
  // reserving symmetrically is what keeps the centring, at the cost of a little book
  // size on very short viewports).
  const band = NAV_EDGE + nav + gap;

  // Solve for the scale against the book's VISIBLE box (page area + frame outset).
  // Horizontally the binding half is the wider one — the 42px right outset.
  const availH = vh - band * 2;
  const availW = vw - vw * SIDE_MARGIN * 2;
  // Floor the scale: below ~172px of viewport height the reserved band exceeds the
  // whole screen and the raw solve goes NEGATIVE, which would mirror the book rather
  // than shrink it. Nothing is usable at that size, but it must not invert.
  const s = Math.max(0.05, Math.min(
    availW / (2 * Math.max(640 + FRAME_L, 640 + FRAME_R)),
    availH / (720 + FRAME_T + FRAME_B)
  ));
  flipScaleEl.style.setProperty("--book-scale", s.toFixed(4));

  // ---- publish the book's real rendered geometry for the controls to anchor to ----
  const cx = vw / 2, cy = vh / 2;                    // .flip-scale is centred on both axes
  const left   = cx - (640 + FRAME_L) * s;
  const right  = cx + (640 + FRAME_R) * s;
  const top    = cy - (360 + FRAME_T) * s;
  const bottom = cy + (360 + FRAME_B) * s;
  const root = document.documentElement.style;
  const px = function (n) { return n.toFixed(2) + "px"; };
  root.setProperty("--book-w", px(right - left));
  root.setProperty("--book-h", px(bottom - top));
  root.setProperty("--book-left",   px(left));       // absolute viewport-space edges
  root.setProperty("--book-right",  px(right));
  root.setProperty("--book-top",    px(top));
  root.setProperty("--book-bottom", px(bottom));
  root.setProperty("--gutter-l", px(left));          // clear room outside each edge
  root.setProperty("--gutter-r", px(vw - right));
  root.setProperty("--gutter-t", px(top));
  root.setProperty("--gutter-b", px(vh - bottom));
  // Resolved --nav-btn, so a test can assert the JS mirror and the CSS token agree.
  root.setProperty("--nav-btn-px", px(nav));

  // Re-glue the page-turn hint. It hangs off the BOOK's right edge (not the forward
  // arrow, despite what this comment used to say), and positionFlipHint reads the
  // book's live rect — so it needed no change for the new anchoring, only this call.
  if (flipHint && flipHint.classList.contains("show")) positionFlipHint();
}

/* ---- Render / stacking for the CSS leaf flip ---------------------------- */
// A TURNED leaf sits to the left (rotateY -180deg, showing its blank back over
// the cover); an UN-turned leaf lies flat on top of the cover. z-index keeps the
// current (top un-turned) page in front, and stacks more-recently turned leaves
// above earlier ones on the left pile.
function updateZ() {
  leaves.forEach(function (leaf, i) {
    leaf.style.zIndex = (i < flipped) ? (200 + i) : (100 - i);
  });
  applyPageWindow();
}

/* ---- GPU PAGE WINDOWING -------------------------------------------------
   Every leaf is a CSS-3D layer with `will-change: transform`, so leaving all of
   them renderable keeps a full-page composited layer alive per page — plus any
   filtered/animated children on faces that are turned away, which is what produces
   ghost overlays bleeding through onto unrelated pages.

   Only the current page and its immediate neighbours (the minimum needed for a
   believable turn, since a turn only ever involves `flipped` and `flipped ± 1`)
   stay renderable. Everything else is released with visibility:hidden +
   will-change:auto + pointer-events:none.

   visibility — NOT display:none — because the leaf stack's geometry and z-ordering
   are what position the page; display:none would collapse it out of the stack. */
const PAGE_WINDOW = 1;
function applyPageWindow() {
  const lo = flipped - PAGE_WINDOW, hi = flipped + PAGE_WINDOW;
  leaves.forEach(function (leaf, i) {
    // A leaf mid-turn must stay renderable even if the window has moved past it.
    const near = (i >= lo && i <= hi) || leaf.classList.contains("flipping");
    leaf.classList.toggle("is-far", !near);
  });
}
function renderLeaves() {
  leaves.forEach(function (leaf, i) {
    if (i < flipped) leaf.classList.add("flipped");
    else             leaf.classList.remove("flipped");
  });
  updateZ();
}

/* ---- Per-page media -----------------------------------------------------
   Play the CURRENT page's video (pause every other), and pop the current page's
   speech bubble in ONCE, only after the page has fully settled. Called after
   each flip completes and once the cover has finished opening. */
let mediaDelayTimer = null;   // pending "start this video after N ms" timer
let mediaDelayIdx = -1;       // which page that pending timer belongs to
let lastMediaIdx = -1;        // last page refreshMedia handled (to arm the pulse once)
let armNextPulse = false;     // allow the Next-arrow glow pulse ONCE per page arrival

function playVideoNow(v) {
  try {
    v.preload = "auto";                       // make sure it's buffering before we play
    if (v.ended) v.currentTime = 0;
    v.muted = false;                          // try WITH sound (primed in the Play gesture)
    const p = v.play();
    if (p && p.catch) p.catch(function () { v.muted = true; v.play().catch(function () {}); });
  } catch (_) {}
}

/* Buffer ONE page's video on demand (only the current + next page are ever
   warmed, so we never spin up all 25 decoders at once). */
function warmVideo(i) {
  const leaf = leaves[i];
  if (!leaf) return;
  const v = leaf.querySelector("video.page-media");
  if (v && v.preload !== "auto") { v.preload = "auto"; try { v.load(); } catch (_) {} }
}

/* Unlock ONE page's video for instant, sound-enabled playback: a muted
   play()→pause() done INSIDE a user gesture. We prime only the page being shown
   and the next one — priming all 25 at once was the opening lag. */
function primeVideo(i) {
  const leaf = leaves[i];
  if (!leaf) return;
  const v = leaf.querySelector("video.page-media");
  if (!v || v.dataset.primed) return;
  v.dataset.primed = "1";
  try {
    v.muted = true; v.preload = "auto";
    const p = v.play();                       // start within the gesture → element is "activated"
    if (p && p.catch) p.catch(function () {});
    v.pause();                                // pause synchronously
    v.currentTime = 0;
  } catch (_) {}
}

function refreshMedia() {
  const idx = flipped;                         // the front-most page right now
  if (idx !== lastMediaIdx) {
    lastMediaIdx = idx;
    armNextPulse = true;                       // arm the Next-arrow glow pulse once per page
    // Re-arm the forward gate for the page we've just landed on. A page the learner
    // has ALREADY cleared once stays cleared (see clearedPages) — going back must not
    // make them sit through the whole video again.
    armForwardGate(idx);
    // ARRIVAL RESET — every video page starts from 0:00 when navigated to. Without
    // this, a page left mid-clip (Next pressed early, then Back — or any revisit)
    // kept its paused timestamp and RESUMED there: picture mid-scene, voiceover
    // mid-sentence. Rewind exactly once per arrival — this block runs only when
    // `flipped` changes — so the flip-end "idempotent safety net" call can never
    // restart a clip that is already playing on this page. The forward gate is
    // untouched: a cleared page stays cleared (armForwardGate above), so the
    // learner is never made to sit through the whole clip again to move on.
    const arrivedLeaf = leaves[idx];
    const arrivedVid = arrivedLeaf && arrivedLeaf.querySelector("video.page-media");
    if (arrivedVid) { try { if (arrivedVid.currentTime > 0) arrivedVid.currentTime = 0; } catch (_) {} }
  }
  // Left the page a delayed video was counting down on? Cancel that countdown.
  if (mediaDelayTimer && mediaDelayIdx !== idx) {
    clearTimeout(mediaDelayTimer); mediaDelayTimer = null; mediaDelayIdx = -1;
  }
  // Buffer + gesture-unlock ONLY this page and the next (so the upcoming flip is
  // instant and keeps sound) — never all 25 videos at once.
  warmVideo(idx); warmVideo(idx + 1); primeVideo(idx + 1);
  // Pause every video that is NOT the current page.
  leaves.forEach(function (leaf, i) {
    if (i === idx) return;
    const v = leaf.querySelector("video.page-media");
    if (v) { try { v.pause(); } catch (_) {} }
  });
  // Start (or schedule) the current page's video.
  const cur = leaves[idx];
  const v = cur && cur.querySelector("video.page-media");
  if (v) {
    const delayMs = (pages[idx] && pages[idx].delay) ? pages[idx].delay : 0;
    if (delayMs > 0) {
      // Already playing this page, or already counting down for it → leave it alone
      // (so the flip-start + flip-end calls don't restart the 3s countdown).
      if (mediaDelayIdx === idx && (mediaDelayTimer || !v.paused)) { /* keep going */ }
      else {
        try { v.pause(); v.currentTime = 0; } catch (_) {}   // hold on the first frame
        mediaDelayIdx = idx;
        mediaDelayTimer = setTimeout(function () {
          mediaDelayTimer = null;
          if (flipped === idx) playVideoNow(v);               // only if still on this page
        }, delayMs);
      }
    } else {
      playVideoNow(v);                          // no delay → instant
    }
  }
  const bub = cur && cur.querySelector(".bubble");
  if (bub && !bub.dataset.revealed) {           // reveal once — "for one time"
    bub.dataset.revealed = "1";
    bub.classList.add("revealed");
  }
  updateLbdOverlay();                           // show/hide the embedded LBD game
  // Right-side page stack shrinks toward the end: 3 sheets → … → 0 on the last page.
  if (pageStackEl) pageStackEl.dataset.count = String(Math.max(0, Math.min(3, totalPages - 1 - flipped)));
  // Restart the idle → page-turn-hint countdown for the page we've just landed on
  // (uses the NEW `flipped`, so the delay is right: 5s on page 1, 10s afterwards).
  if (typeof resetIdleHint === "function") resetIdleHint();
}

/* ==========================================================================
   FORWARD GATE  —  ONE guard that every forward route must pass.
   --------------------------------------------------------------------------
   Two independent requirements per page, each only applied when the page
   actually has it:

     firstPageVideoCompleted        the page's own video reached its end — or was
                                    released by its `error` event, or by a watchdog
                                    of (duration + 4s), or 30s when the duration is
                                    unknown. Three release paths, always.
     firstPageInteractionCompleted  the page's required learner activity was
                                    SUCCESSFULLY completed. A wrong tap, or merely
                                    starting the activity, does not count. Pages
                                    with no activity start this as true.

   On the FIRST story page the Next arrow is not merely disabled — it is absent
   until both are satisfied, and Back is absent entirely (there is no previous page:
   the cover is not one). On a GAME page the arrow is likewise absent until the game
   reports completion, because finishing the game is the only route forward and a
   visible-but-dead arrow there reads as a way to skip it. On the remaining video
   pages Next is present but disabled until that page's video finishes.

   ONE-TIME ONLY: a page the learner has already cleared is recorded in clearedPages
   and arrives UNLOCKED on every later visit, so paging back through the story shows
   both arrows immediately instead of making them watch each video (or replay each
   game) again. The set is emptied by resetToStart(), so a fresh read from the cover
   gates every page properly again.

   canNavigateForward() is the single state guard: the Next arrow, the keyboard,
   swipe/drag, the page corners and every programmatic turn all consult it, so
   disabling the visible button can never be the only lock.
   ========================================================================== */
let firstPageVideoCompleted       = false;
let firstPageInteractionCompleted = false;
/* Page indices whose gate has been satisfied at least once this read-through. */
const clearedPages = new Set();
let gateArmedIdx  = -1;      // which page the current gate belongs to
let gateVideoEl   = null;    // the video element the gate is listening to
let gateWatchdog  = null;    // (duration + 4s) / 30s release timer
let gateOnEnded   = null;    // retained so the listeners can be removed cleanly
let gateOnError   = null;

const GATE_WATCHDOG_PAD_MS = 4000;
const GATE_WATCHDOG_DEFAULT_MS = 30000;

function pageHasVideo(i)       { return !!(pages[i] && pages[i].type === "video"); }
/* A game page ALWAYS owns a required activity — finishing the game — whether or not
   its config entry remembers to say `interactive: true`. Deriving it from the type
   means a newly added game page can never ship with an open gate. */
function pageHasInteraction(i) {
  return !!(pages[i] && (pages[i].interactive || pages[i].type === "lbd"));
}

/* Drop the previous page's listeners and timers. Without this, a watchdog armed on
   page 2 could fire while the learner is on page 3 and unlock the wrong page. */
function disarmForwardGate() {
  clearTimeout(gateWatchdog);
  gateWatchdog = null;
  // Clear the completion flags too. Leaving them set meant that after Home from the
  // first story page, updateNavControls() still saw "both requirements met" and
  // revealed the Next arrow on the COVER.
  firstPageVideoCompleted = false;
  firstPageInteractionCompleted = false;
  if (gateVideoEl) {
    if (gateOnEnded) gateVideoEl.removeEventListener("ended", gateOnEnded);
    if (gateOnError) gateVideoEl.removeEventListener("error", gateOnError);
  }
  gateVideoEl = null; gateOnEnded = null; gateOnError = null;
  gateArmedIdx = -1;
}

/* (Re-)arm the gate for a page. Called on EVERY arrival, including arriving
   backwards. A page that was cleared earlier in this read-through arrives already
   open (clearedPages); anything else starts locked rather than inheriting a stale
   "already finished" flag from a different page. */
function armForwardGate(idx) {
  disarmForwardGate();
  gateArmedIdx = idx;
  // Drop the previous page's "turn the page" arrow cue. A CSS animation outranks the
  // [disabled] opacity rule, so a leftover blink would leave the NEW page's locked
  // Next arrow pulsing at full brightness — reading as available when it isn't.
  stopNextPulse();
  if (cornerNext) cornerNext.classList.remove("blink");

  // A page with no video has nothing to wait for; same for a page with no activity.
  // A page already cleared once has nothing left to wait for at all.
  const alreadyCleared = clearedPages.has(idx);
  firstPageVideoCompleted       = alreadyCleared || !pageHasVideo(idx);
  firstPageInteractionCompleted = alreadyCleared || !pageHasInteraction(idx);

  if (pageHasVideo(idx) && !alreadyCleared) {
    const leaf = leaves[idx];
    const v = leaf && leaf.querySelector("video.page-media");
    if (!v) {
      // The element is missing entirely — never lock a page we can't observe.
      firstPageVideoCompleted = true;
    } else {
      gateVideoEl = v;
      gateOnEnded = function () { releaseVideoGate(idx, "ended"); };
      gateOnError = function () { releaseVideoGate(idx, "error"); };
      v.addEventListener("ended", gateOnEnded);
      v.addEventListener("error", gateOnError);
      // A video that already errored before we attached (e.g. a broken src) would
      // never fire again — check the element's current state too.
      if (v.error) {
        releaseVideoGate(idx, "error(already)");
      } else {
        const known = isFinite(v.duration) && v.duration > 0 ? v.duration * 1000 : 0;
        gateWatchdog = setTimeout(function () {
          releaseVideoGate(idx, "watchdog");
        }, known ? known + GATE_WATCHDOG_PAD_MS : GATE_WATCHDOG_DEFAULT_MS);
        // `duration` is often NaN until metadata arrives — re-arm the watchdog with
        // the real duration once it's known, so a long clip isn't cut off at 30s.
        if (!known) {
          v.addEventListener("loadedmetadata", function onMeta() {
            v.removeEventListener("loadedmetadata", onMeta);
            if (gateArmedIdx !== idx || firstPageVideoCompleted) return;
            if (!(isFinite(v.duration) && v.duration > 0)) return;
            clearTimeout(gateWatchdog);
            gateWatchdog = setTimeout(function () {
              releaseVideoGate(idx, "watchdog");
            }, v.duration * 1000 + GATE_WATCHDOG_PAD_MS);
          });
        }
      }
    }
  }
  updateNavControls();
}

/* Both requirements met for `idx`? Remember it, so returning to this page later
   arrives unlocked, and play the arrow's glow cue now that it is really available. */
function noteGateSatisfied(idx) {
  if (gateArmedIdx !== idx) return;
  if (!(firstPageVideoCompleted && firstPageInteractionCompleted)) return;
  clearedPages.add(idx);
  pulseNextArrow();
}

function releaseVideoGate(idx, why) {
  if (gateArmedIdx !== idx) return;            // stale timer from a page we've left
  if (firstPageVideoCompleted) return;
  firstPageVideoCompleted = true;
  clearTimeout(gateWatchdog);
  gateWatchdog = null;
  if (why !== "ended") {
    console.warn("[flipbook] page " + (idx + 1) + " video gate released via " + why +
                 " — the learner is not blocked.");
  }
  updateNavControls();
  noteGateSatisfied(idx);                      // after the arrow's state is current
}

/* Called by a page activity when the learner SUCCESSFULLY completes it. Starting the
   activity, or getting it wrong, must not call this. */
function markInteractionComplete(idx) {
  if (idx == null) idx = flipped;
  if (gateArmedIdx !== idx) return;
  if (firstPageInteractionCompleted) return;
  firstPageInteractionCompleted = true;
  updateNavControls();
  noteGateSatisfied(idx);
}

/* ---- The Next arrow's "you can turn the page now" GLOW PULSE --------------
   Fired the moment the arrow becomes genuinely available (gate open, visible, not
   disabled) — never while it is still hidden or greyed. Three quick glowing swells,
   then the class comes off and the arrow sits in its normal resting state. Once per
   page arrival, so a short clip can't pulse repeatedly. */
const NEXT_PULSE_MS = 1800;   // keep in sync with .corner-arrow.glow-pulse in styles.css
let nextPulseTimer = null;

function stopNextPulse() {
  clearTimeout(nextPulseTimer);
  nextPulseTimer = null;
  if (cornerNext) cornerNext.classList.remove("glow-pulse");
}

function pulseNextArrow() {
  if (!cornerNext || !armNextPulse) return;
  if (!opened || !ready || lbdFullscreen) return;
  // Only cue a button the learner can actually see and press.
  if (!cornerNext.classList.contains("is-visible") || cornerNext.disabled) return;
  armNextPulse = false;                        // one pulse per page arrival
  clearTimeout(nextPulseTimer);
  cornerNext.classList.remove("glow-pulse");
  void cornerNext.offsetWidth;                 // commit, so the animation restarts cleanly
  cornerNext.classList.add("glow-pulse");
  nextPulseTimer = setTimeout(function () {
    cornerNext.classList.remove("glow-pulse"); // ...and back to the normal state
    nextPulseTimer = null;
  }, NEXT_PULSE_MS + 60);
}

/* THE single forward guard. */
function canNavigateForward() {
  if (!opened || !ready || animating) return false;
  if (lbdFullscreen) return false;                 // the game owns the screen
  if (flipped >= totalPages - 1) return false;     // already on THE END
  if (gateArmedIdx !== flipped) return false;      // gate not armed for this page yet
  return firstPageVideoCompleted && firstPageInteractionCompleted;
}

/* A shut gate now hides the Next arrow OUTRIGHT on EVERY page, rather than parking a
   greyed-out one on the page:
     • the first story page  — the spec's rule;
     • every game page       — completing the game is the only route forward, so a
                               dead arrow sitting there reads as a way to skip it;
     • every video page      — the arrow used to sit there ghosted at opacity .22 from
                               the moment the page landed and then fade up to full over
                               400ms when the clip ended. The button should ARRIVE when
                               the video ends, not fade in on a page it was already on.
   Pages with nothing to satisfy have an open gate from the start, so this never hides an
   arrow the learner is entitled to — `show` in updateNavControls() only consults this
   while the gate is actually shut. */
function nextArrowHiddenWhileLocked(i) {
  return true;
}

/* ---- Navigation (drives the CSS leaf flip) ------------------------------ */
function turnLeaf(leaf) {                 // shared flip visuals + timing
  leaf.style.zIndex = 300;               // lift the turning sheet above everything
  leaf.classList.add("flipping");        // enables the moving curl shading
  renderLeaves();
  refreshMedia();                        // START now → the target video plays INSTANTLY
                                          // (as the page is revealed, not after the flip)
  playFlip();
  updateProgress();
  setTimeout(function () {
    leaf.classList.remove("flipping");
    animating = false; updateZ(); updateProgress();
    refreshMedia();                      // re-assert once settled (idempotent safety net)
  }, FLIP_MS + 40);
}
/* Forward. `internal` is used ONLY by the game-completion path, where the game
   finishing IS the gate release; every learner-facing route goes through the gate.
   `animating` doubles as the one-page-per-turn lock: it is set synchronously here,
   so a double-tap or a held key cannot skip two pages. */
function goNext(internal) {
  if (!opened || !ready || animating) return;   // wait until the cover has fully opened
  if (flipped >= totalPages - 1) return;         // already on the LAST page (THE END)
  if (!internal && !canNavigateForward()) return;
  animating = true;
  const leaf = leaves[flipped];                  // the page to turn
  flipped++;
  turnLeaf(leaf);
}
function goPrev() {
  if (!opened || !ready || animating) return;   // wait until the cover has fully opened
  if (lbdFullscreen) return;                    // no page turns under a live game
  if (flipped <= 0) return;               // already on the first page
  animating = true;
  flipped--;
  turnLeaf(leaves[flipped]);
}

/* ---- Nav state ---------------------------------------------------------- */
function updateNavControls() {
  const onEnd = flipped >= totalPages - 1;
  const firstStoryPage = flipped === 0;

  // On the cover / start screen NOTHING is shown, whatever the gate flags happen to say.
  // This is the single invariant that keeps Home, Replay and a fresh load consistent.
  if (!opened) {
    [cornerPrev, cornerNext].forEach(function (b) {
      if (!b) return;
      b.classList.remove("is-visible");
      b.setAttribute("aria-hidden", "true");
      b.disabled = true;
    });
    return;
  }

  // BACK is completely ABSENT on the first story page — not disabled, not faded.
  if (cornerPrev) {
    cornerPrev.classList.toggle("is-hidden", firstStoryPage);
    cornerPrev.classList.toggle("is-visible", opened && !firstStoryPage);
    cornerPrev.disabled = !ready || flipped <= 0;
    cornerPrev.setAttribute("aria-hidden", String(firstStoryPage));
  }

  // NEXT: absent while this page's gate is shut (nextArrowHiddenWhileLocked), so it
  // ARRIVES the moment the video ends instead of sitting there greyed and fading up.
  // A page already cleared once arrives with the gate open, so paging back shows a
  // live arrow immediately.
  if (cornerNext) {
    const gateOpen = firstPageVideoCompleted && firstPageInteractionCompleted;
    const show = !onEnd && (gateOpen || !nextArrowHiddenWhileLocked(flipped));
    cornerNext.classList.toggle("is-visible", show);
    cornerNext.disabled = !ready || onEnd || !gateOpen;
    cornerNext.setAttribute("aria-hidden", String(!show));
    cornerNext.setAttribute("aria-disabled", String(!!cornerNext.disabled));
    if (!show) stopNextPulse();      // never leave a glow running on a hidden arrow
  }
}
/* Kept as an alias: several call sites read as "the page changed, refresh chrome". */
function updateProgress() { updateNavControls(); }

/* ---- Fullscreen: go FULLSCREEN when the book opens (the Play tap is the user
   gesture the Fullscreen API requires) and LEAVE fullscreen when back at the
   cover (Home / Replay). Applies on every screen; silently no-ops where the
   browser blocks it (e.g. iPhone Safari can't fullscreen arbitrary elements). */
function enterFullscreen() {
  try {
    if (document.fullscreenElement || document.webkitFullscreenElement) return;
    var el = document.documentElement;
    var req = el.requestFullscreen || el.webkitRequestFullscreen || el.webkitRequestFullScreen || el.msRequestFullscreen;
    if (req) { var p = req.call(el); if (p && p.catch) p.catch(function () {}); }
  } catch (_) {}
}
function exitFullscreen() {
  try {
    if (!(document.fullscreenElement || document.webkitFullscreenElement)) return;
    var ex = document.exitFullscreen || document.webkitExitFullscreen || document.webkitCancelFullScreen || document.msExitFullscreen;
    if (ex) { var p = ex.call(document); if (p && p.catch) p.catch(function () {}); }
  } catch (_) {}
}

/* ---- Open the 3D cover, then hand off to the page-turning book ----------
   Shared by the first open (openBook) AND Replay (replayBook), so the dramatic
   hinge-open + post-open setup are identical both times. */
function runOpenSequence() {
  ready = false;
  document.body.classList.remove("is-closing");
  document.body.classList.add("is-open");
  // The whole open motion IS the cover's own hinge — NO zoom / camera move.
  book.classList.remove("closing");
  book.classList.add("open");          // cover hinges open on the LEFT spine
  bookFloat.classList.add("rest");     // stop the idle bob
  coverScene.classList.remove("parked");
  flipbookEl.style.zIndex = "";        // cover ABOVE the pages while it swings open
  // Reveal the REAL page right away (it sits beneath the cover, masked by it).
  flipbookEl.classList.add("show");
  // A user gesture drives every open, so start audio here.
  soundOn();
  resumeAudio();
  playCoverFlip();
  playBgMusic();                        // start the looping background music
  primeVideo(0); primeVideo(1);         // unlock page 1 + 2 inside the gesture
  refreshMedia();                       // start the page-1 video right away
  // Once the cover has FULLY opened, park it, lift the pages above it, hand over
  // pointer events, and mark the book READY.
  clearTimeout(_openTimer);
  _openTimer = setTimeout(function () {
    coverScene.classList.add("parked");
    flipbookEl.style.zIndex = "5";        // pages now sit ABOVE the parked cover (z3)
    tapCatcher.style.pointerEvents = "none";
    flipbookEl.style.pointerEvents = "auto";
    ready = true;
    updateProgress();
    refreshMedia();
    resetIdleHint();
  }, COVER_OPEN_MS + 50);
  updateProgress();
}
function openBook() {
  if (opened) return;
  // STAGE A GATE — the single choke point. Keyboard, touch, the tap-catcher, a direct
  // openBook() call and any synthetic call all land here, so nothing can start the
  // experience before the shell assets are in place.
  if (window.FlipbookPreload && !window.FlipbookPreload.startAllowed) return;
  opened = true;
  enterFullscreen();          // Play tap is a user gesture → allowed to go fullscreen
  runOpenSequence();
}

/* ---- Reset the whole book to the START SCREEN: the CLOSED FRONT COVER + Play
   button, exactly like a fresh load (so tapping Play reads from the top). Shared
   by Replay and Home (called once the closing swing has finished). --------- */
function resetToStart() {
  exitFullscreen();           // back at the cover → leave fullscreen
  teardownLbd();              // no overlay, no game audio, no stale fullscreen classes
  disarmForwardGate();        // drop any pending video watchdog from the page we left
  clearedPages.clear();       // a fresh read from the cover gates every page again
  stopNextPulse();
  ready = false; opened = false; flipped = 0;
  renderLeaves();
  leaves.forEach(function (leaf) {
    var vv = leaf.querySelector("video.page-media");
    if (vv) { try { vv.pause(); vv.currentTime = 0; } catch (_) {} }
  });
  lastMediaIdx = -1;
  document.body.classList.remove("is-open", "is-closing");
  book.classList.remove("open", "closing");
  coverScene.classList.remove("parked");
  cover.style.transform = "";                 // cover CLOSED → front cover + Play button showing
  flipbookEl.classList.remove("show");         // pages hidden behind the closed cover
  flipbookEl.style.zIndex = "";
  flipbookEl.style.pointerEvents = "none";
  bookFloat.classList.remove("rest");          // resume the idle bob
  tapCatcher.style.pointerEvents = "auto";     // Play is tappable again
  hideFlipHint(); clearTimeout(idleHintTimer); clearTimeout(nudgeHideTimer);
  // Stop music (restarts on Play) and clear any duck left over from a page video that
  // was narrating when the book closed, so the next Play starts at the normal level.
  if (bgFadeTimer) { clearInterval(bgFadeTimer); bgFadeTimer = null; }
  try { bgMusic.pause(); bgMusic.currentTime = 0; } catch (_) {}
  applyBgLevel(BG_VOL_IDLE);
  updateProgress();                            // hides the progress read-out (not opened)
}

/* ---- CLOSE THE BOOK: the cover swings SHUT — the exact REVERSE of the opening
   hinge (cover −180 → 0) — and the book lands on the front cover. Reached ONLY by
   REPLAY on THE END page now that the Home button is gone. `afterReset` runs once
   we're back on the cover. ------------------------------------------------- */
function closeBookToCover(afterReset) {
  ready = false;                               // block flips during the close
  teardownLbd();                               // overlay + game audio go NOW, not in 2s
  clearTimeout(_openTimer);
  clearTimeout(_homeTimer);
  hideFlipHint(); clearTimeout(idleHintTimer); clearTimeout(nudgeHideTimer);
  stopNextPulse();
  if (cornerNext) cornerNext.classList.remove("blink");
  var v = currentVideo(); if (v) { try { v.pause(); } catch (_) {} }
  // pages back UNDER the cover, so the closing cover sweeps over them
  flipbookEl.style.zIndex = "";
  flipbookEl.style.pointerEvents = "none";
  tapCatcher.style.pointerEvents = "none";
  coverScene.classList.remove("parked");
  // CLOSE — reverse of the opening hinge (cover swings from -180 back to 0).
  // is-closing keeps the current page bright (hides the dark thickness block) and
  // hides the turned-page pile, so the cover folds cleanly with no stray left page.
  document.body.classList.add("is-closing");
  book.classList.remove("open");
  book.classList.add("closing");
  playCoverFlip();
  _homeTimer = setTimeout(function () {
    resetToStart();
    if (typeof afterReset === "function") afterReset();
  }, COVER_CLOSE_MS + 60);
}

/* ---- REPLAY (button on THE END page): close the book with the reverse-of-open
   swing, land on the front cover, and re-arm the title VO for another read. */
function replayBook() {
  if (!opened || animating) return;
  teardownLbd();                     // Replay from THE END must not leave a game alive
  closeBookToCover();
}

/* (goHome() was REMOVED with the Home button — it had exactly one caller, that
   button's click handler. Replay still reaches closeBookToCover(); its mid-open
   `!ready` shortcut is unreachable from THE END page, which only exists once the
   cover has finished opening.) */

/* ==========================================================================
   INPUT  —  tap PLAY to OPEN the cover; once open, drag + corner arrows +
   keyboard drive the page flip.
   ========================================================================== */
const tapCatcher = document.getElementById("tapCatcher");

// The book opens ONLY from the play button. The tap-catcher still sits on top to
// block page gestures before opening, but it opens the book only when the tap
// lands inside the play button's (breathing) hit-circle — taps elsewhere on the
// cover do nothing.
function tapHitsPlay(e) {
  const r = hint.getBoundingClientRect();
  const cx = r.left + r.width / 2, cy = r.top + r.height / 2;
  const rad = Math.max(r.width, r.height) / 2;
  return Math.hypot(e.clientX - cx, e.clientY - cy) <= rad;
}
if (tapCatcher) tapCatcher.addEventListener("click", function (e) { if (!opened && tapHitsPlay(e)) openBook(); });
// Show the hand (pointer) cursor ONLY when hovering the play button — the sole CTA
// on the cover. Everywhere else on the tap surface stays a normal cursor.
if (tapCatcher) tapCatcher.addEventListener("mousemove", function (e) {
  tapCatcher.style.cursor = (!opened && tapHitsPlay(e)) ? "pointer" : "default";
});

// The play button itself (also covers keyboard: Enter/Space on the focused button).
hint.addEventListener("click", function (e) { e.stopPropagation(); if (!opened) openBook(); });

// Bottom-corner flip arrows (outside the book): back = left, forward = right. These
// are the ONLY prev/next controls; the keyboard handler below calls goPrev/goNext
// directly, so it was never wired to the removed #prev/#next pair.
cornerPrev.addEventListener("click", function (e) { e.stopPropagation(); goPrev(); this.blur(); });
cornerNext.addEventListener("click", function (e) { e.stopPropagation(); goNext(); this.blur(); });
if (replayBtn) replayBtn.addEventListener("click", function (e) { e.stopPropagation(); replayBook(); this.blur(); });

// Page interaction — DRAG TO TURN: grab the page and it follows your cursor,
// rotating about the spine, then SNAPS to the nearest state when you let go.
//   • drag LEFT  → turn the current page forward (it comes to rest on the cover)
//   • drag RIGHT → turn the previous page back
// A plain tap does nothing; the corner arrows + keyboard still work.
(function () {
  let startX = 0, startY = 0, pw = 1;
  let leaf = null, dir = 0, decided = false, dragging = false, curlEl = null;
  let lastX = 0, lastT = 0, vx = 0;                   // for flick (velocity) detection
  const DECIDE = 6;                                   // px before we commit to a drag
  const FLICK = 0.45;                                 // px/ms — a quick flick completes the turn
  const FINISH_DEG = 45;                              // turned this far (deg) → completes on release

  // how many degrees the drag has turned the page (0..180)
  function degFromDx(dx) { return Math.max(0, Math.min(180, Math.abs(dx) / pw * 180)); }
  // the live angle for the active leaf, given the raw horizontal travel
  function liveAngle(dx) {
    return (dir === 1) ? degFromDx(Math.min(0, dx))          // forward: leftward turns 0→180
                       : 180 - degFromDx(Math.max(0, dx));   // back: starts at 180, rightward → 0
  }

  flipbookEl.addEventListener("pointerdown", function (e) {
    if (!opened || !ready || animating) return;
    if (lbdFullscreen) return;                        // no dragging pages under a live game
    startX = e.clientX; startY = e.clientY;
    lastX = e.clientX; lastT = e.timeStamp || performance.now(); vx = 0;
    decided = false; dragging = true; leaf = null; dir = 0; curlEl = null;
    pw = flipbookEl.getBoundingClientRect().width || 1;
  });

  flipbookEl.addEventListener("pointermove", function (e) {
    if (!dragging) return;
    const now = e.timeStamp || performance.now();
    const dt = now - lastT;
    if (dt > 0) vx = (e.clientX - lastX) / dt;         // running horizontal velocity
    lastX = e.clientX; lastT = now;
    const dx = e.clientX - startX, dy = e.clientY - startY;
    if (!decided) {
      if (Math.abs(dx) < DECIDE || Math.abs(dx) <= Math.abs(dy)) return;   // wait for a clear horizontal drag
      // SWIPE / DRAG respects the SAME gate as the button and the keyboard: a forward
      // drag on a page whose video hasn't finished simply never engages, so disabling
      // the visible arrow is never the only lock.
      if (dx < 0 && canNavigateForward())     { dir = 1;  leaf = leaves[flipped]; }     // turn forward (stop at THE END page)
      else if (dx > 0 && flipped > 0)         { dir = -1; leaf = leaves[flipped - 1]; } // turn back
      else { dragging = false; return; }                  // nothing to turn that way
      decided = true;
      leaf.style.transition = "none";                     // follow the finger exactly
      leaf.style.zIndex = 300;
      curlEl = leaf.querySelector(".curl");
      try { flipbookEl.setPointerCapture(e.pointerId); } catch (_) {}
    }
    const ang = Math.max(0, Math.min(180, liveAngle(dx)));
    leaf.style.transform = "rotateY(" + (-ang) + "deg)";
    if (curlEl) curlEl.style.opacity = (ang <= 90 ? ang / 90 : (180 - ang) / 90) * 0.9;
  });

  function endDrag(e) {
    if (!dragging) return;
    dragging = false;
    const L = leaf, D = dir, C = curlEl;
    leaf = null; curlEl = null;
    if (!decided || !L) return;                           // a plain tap → nothing

    const ang = Math.max(0, Math.min(180, liveAngle(e.clientX - startX)));
    // Complete the turn if it's been dragged far enough OR flicked quickly in
    // the turn's direction — no need to drag all the way past halfway.
    const flick = (D === 1) ? (vx < -FLICK) : (vx > FLICK);
    const complete   = (D === 1) ? (ang > FINISH_DEG || flick)
                                 : (ang < 180 - FINISH_DEG || flick);
    const endFlipped = (D === 1) ? complete   : !complete;    // does this leaf end up turned?

    animating = true;
    if (C) C.style.opacity = "";
    if (complete) { playFlip(); flipped += (D === 1) ? 1 : -1; }
    // Lock in the resting classes + z-index NOW (so nothing pops in later), then
    // animate the inline transform from the dragged angle to the target. The
    // .flipped class already holds the same final angle underneath.
    L.style.transition = "";                              // restore the CSS flip transition
    void L.offsetWidth;                                   // reflow so it animates FROM the dragged angle
    L.classList.add("flipping");                          // curl shading during the snap
    renderLeaves();                                       // apply .flipped + z-index immediately
    refreshMedia();                                       // START the target video INSTANTLY
    L.style.transform = endFlipped ? "rotateY(-180deg)" : "rotateY(0deg)";
    updateProgress();

    setTimeout(function () {
      L.classList.remove("flipping");
      // Drop the inline transform WITHOUT re-animating: the .flipped class already
      // holds the final angle, so disabling the transition for this swap prevents
      // the leaf from briefly swinging back (the "page reappears on the left" glitch).
      L.style.transition = "none";
      L.style.transform = "";
      void L.offsetWidth;                                 // commit with no transition
      L.style.transition = "";                            // restore for the next turn
      animating = false; updateProgress();
      refreshMedia();                                     // re-assert once settled (idempotent safety net)
    }, FLIP_MS + 40);
  }
  flipbookEl.addEventListener("pointerup", endDrag);
  flipbookEl.addEventListener("pointercancel", endDrag);
})();

window.addEventListener("keydown", function (e) {
  // While the game owns the screen, no key may turn a story page underneath it.
  if (lbdFullscreen) return;
  // goNext() consults canNavigateForward(), so the keyboard is gated exactly like
  // the arrow — it can never be the route that bypasses an unfinished video.
  if (e.key === "ArrowRight") { e.preventDefault(); opened ? goNext() : openBook(); }
  else if (e.key === "ArrowLeft") { e.preventDefault(); goPrev(); }
  else if ((e.key === " " || e.key === "Enter") && !opened) { e.preventDefault(); openBook(); }
});

// Keep the canvas scaled to fit on resize / rotate.
let _resizeSettle = null;
function onViewportChange() {
  // Suppress the page-turn transitions while the viewport is actively changing, so
  // a rapid resize / resolution change can't make the book LOOK like it's auto-
  // flipping (the leaves re-render during the scale change). Restored once settled.
  document.body.classList.add("is-resizing");
  clearTimeout(_resizeSettle);
  _resizeSettle = setTimeout(function () { document.body.classList.remove("is-resizing"); }, 220);
  fitScale();
  // Re-park the LBD overlay over the (re-scaled) page — unless it's fullscreen,
  // where it already fills the viewport via CSS.
  if (lbdOverlay && lbdOverlay.classList.contains("visible") && !lbdFullscreen) positionLbdOverlay();
  applyPageWindow();      // re-window after a resize / orientation change
}
window.addEventListener("resize", onViewportChange);
window.addEventListener("orientationchange", onViewportChange);

/* ---- Block ALL zoom (pinch, double-tap, ctrl+wheel, ctrl +/-) ------------
   The book is fixed-layout, so zoom would only break it. */
(function () {
  // Never let anything (esp. page images) start a native HTML5 drag — that was
  // showing a "ghost" of the image following the cursor during a page-flip drag.
  document.addEventListener("dragstart", function (e) { e.preventDefault(); });
  ["gesturestart", "gesturechange", "gestureend"].forEach(function (t) {   // iOS pinch
    document.addEventListener(t, function (e) { e.preventDefault(); }, { passive: false });
  });
  window.addEventListener("wheel", function (e) {                          // desktop ctrl+wheel
    if (e.ctrlKey) e.preventDefault();
  }, { passive: false });
  window.addEventListener("keydown", function (e) {                        // ctrl/⌘ +/-/0
    if ((e.ctrlKey || e.metaKey) && ["+", "-", "=", "0"].indexOf(e.key) !== -1) e.preventDefault();
    // Block "Save page" (Ctrl/⌘+S) — a casual way to grab the media.
    if ((e.ctrlKey || e.metaKey) && (e.key === "s" || e.key === "S")) e.preventDefault();
  });
  document.addEventListener("touchmove", function (e) {                    // 2-finger pinch
    if (e.touches && e.touches.length > 1) e.preventDefault();
  }, { passive: false });

  // NOTE: the right-click / context menu is intentionally LEFT ENABLED (so "Inspect"
  // and dev tools work). Casual image protection still stands via CSS — no drag,
  // no text-selection, no iOS long-press "Save Image" callout — plus Ctrl+S is blocked.
})();

/* ==========================================================================
   SOUND  —  Ogg/Opus one-shots in sfx/: "Page flip.ogg" (every page flip) and
   "cover page flip.ogg" (the cover opening), both normally played from the inlined
   base64 in sfx-data.js via Web Audio; plus the looping background theme at 20%.
   All muted until the book is opened (a user gesture).
   ========================================================================== */
let muted = true;

/* NOTE — the title voice-over was REMOVED. It pointed at "sfx/the story night.ogg",
   a file that was never shipped with the project, so every load fired a 404 plus a
   rejected play() and no sound ever came out. Rather than keep a broken reference,
   the whole path is gone. To bring it back, drop the clip into sfx/, add it to the
   `shell` list in tools/gen-manifest.js, and play it from runOpenSequence() — which
   is inside the Play gesture, so the browser will allow it audibly on the first try. */

// Looping BACKGROUND MUSIC — the SAME theme the LBD game uses, played across the
// flipbook pages at 20% volume (per request). Started on open (a user gesture) so
// the browser allows it to play with sound; paused while the game is on screen (the
// game plays this theme itself, louder) — see setLbdFullscreen().
const bgMusic = new Audio("LBD%201/audios/themeMusic.ogg");
bgMusic.loop = true;
// DUCKING: the story pages' voice-over lives in the video's own audio track, and at a
// flat 10% the music still fought it. So the music sits at 10% only when nothing is
// narrating, and drops to 3% for as long as a page video is actually playing — the
// narration stays effortless to follow for a young learner, with the bed still there.
const BG_VOL_IDLE   = 0.10;                 // 10% — no voice-over on screen
const BG_VOL_DUCKED = 0.03;                 // 3%  — while a page video narrates
// iOS/iPadOS Safari IGNORES writes to HTMLMediaElement.volume (the property is
// effectively read-only there), so on tablets the theme played at FULL gain over the
// narration no matter what the two constants above said. The level therefore goes
// through a Web Audio GainNode (wired in initSfx below), which every platform honours;
// the element's own volume stays as the fallback for the no-Web-Audio path.
let bgLevel = BG_VOL_IDLE;                  // the level we WANT right now (gain node or el.volume)
let bgGain = null;                          // GainNode once the Web Audio route is wired
function applyBgLevel(v) {
  bgLevel = Math.max(0, Math.min(1, v));
  if (bgGain) { try { bgGain.gain.value = bgLevel; } catch (_) {} }
  else { try { bgMusic.volume = bgLevel; } catch (_) {} }
}
applyBgLevel(BG_VOL_IDLE);
// preload="none", NOT "auto": this file is 3.8 MB and with "auto" the browser pulled
// all of it during boot, competing with the shell assets the Start button waits on —
// for a track that cannot legally play until the learner taps Play anyway. Stage B
// warms it into the HTTP cache first (priority 0), so play() is served from cache.
bgMusic.preload = "none";
function playBgMusic() {
  try {
    const p = bgMusic.play();
    if (p && p.catch) p.catch(function () {});   // ignore autoplay rejections
  } catch (_) {}
}

/* Fade the music between the two levels over ~250 ms — a hard jump to 3% (and back)
   is audible as a click in the bed, a slide is not. */
let bgFadeTimer = null;
function setBgDuck(on) {
  const target = on ? BG_VOL_DUCKED : BG_VOL_IDLE;
  if (bgFadeTimer) { clearInterval(bgFadeTimer); bgFadeTimer = null; }
  const from = bgLevel, steps = 10;
  let i = 0;
  bgFadeTimer = setInterval(function () {
    i++;
    applyBgLevel(from + (target - from) * (i / steps));
    if (i >= steps) { clearInterval(bgFadeTimer); bgFadeTimer = null; }
  }, 25);
}
/* Media events (play / pause / ended) do NOT bubble, but they DO reach a
   capture-phase listener on the document — one pair of handlers therefore covers
   every page video, including the ones built later, with no per-element wiring. */
function isPageVideo(t) { return t && t.tagName === "VIDEO" && t.classList.contains("page-media"); }
// A muted play() is either the priming trick or an autoplay fallback with no audible
// voice-over — neither should touch the music.
document.addEventListener("play",  function (e) { if (isPageVideo(e.target) && !e.target.muted) setBgDuck(true); }, true);
document.addEventListener("pause", function (e) { if (isPageVideo(e.target)) setBgDuck(false); }, true);
document.addEventListener("ended", function (e) { if (isPageVideo(e.target)) setBgDuck(false); }, true);
// UNMUTE-WITHOUT-PLAY: when the auto-start's audio was blocked, the video is already
// PLAYING muted and the tap-to-hear handler only flips `muted` — play() on an already
// playing element fires no new "play" event, so the duck above never engaged and the
// music sat at idle level over the narration. muted flips fire "volumechange".
document.addEventListener("volumechange", function (e) {
  if (isPageVideo(e.target) && !e.target.paused && !e.target.ended) setBgDuck(!e.target.muted);
}, true);

/* ---- Pause ALL audio when the tab / window goes to the background -----------
   Background music AND the current page's video (its voice-over) must stop the
   moment the reader switches tab or app, and resume when they come back — they
   were continuing to play in the background. Covers visibilitychange (tab switch),
   blur (other window), and pagehide (mobile app switch / bfcache). */
let _bgWasPlaying = false;
function currentVideo() {
  const leaf = leaves[flipped];
  return leaf ? leaf.querySelector("video.page-media") : null;
}
function pauseAllAudioFB() {
  if (!bgMusic.paused) { _bgWasPlaying = true; try { bgMusic.pause(); } catch (_) {} }
  const v = currentVideo();
  if (v && !v.paused) { v.dataset.wasPlaying = "1"; try { v.pause(); } catch (_) {} }
  if (audioCtx && audioCtx.state === "running") { try { audioCtx.suspend(); } catch (_) {} }
}
function resumeAllAudioFB() {
  if (document.hidden || !document.hasFocus()) return;   // only when truly back in front
  if (!opened) return;                                   // nothing plays before the book opens
  if (audioCtx && audioCtx.state === "suspended") { try { audioCtx.resume(); } catch (_) {} }
  if (_bgWasPlaying) { _bgWasPlaying = false; playBgMusic(); }
  const v = currentVideo();
  if (v && v.dataset.wasPlaying && !v.ended) { delete v.dataset.wasPlaying; const p = v.play(); if (p && p.catch) p.catch(function () {}); }
}
document.addEventListener("visibilitychange", function () {
  if (document.hidden) pauseAllAudioFB(); else resumeAllAudioFB();
});
/* "blur" alone is NOT "the user left the page": clicking anywhere inside the embedded
   game's iframe moves focus into that child browsing context, which fires a parent
   window blur even though the app is still front-most — pausing here made the music
   cut out on every tap inside the game frame (and resume on a tap outside it).
   The focus move settles AFTER the blur event, so decide on the next tick:
   if this document still has focus (the focused element is our iframe — hasFocus()
   counts embedded content) the reader never left, and the music plays on. A real
   switch to another window/app leaves hasFocus() false → pause as before. */
window.addEventListener("blur", function () {
  setTimeout(function () {
    if (document.hasFocus() || document.activeElement === lbdFrame) return;
    pauseAllAudioFB();
  }, 0);
});
window.addEventListener("focus", resumeAllAudioFB);
window.addEventListener("pagehide", pauseAllAudioFB);

/* ---- One-shot SFX via Web Audio (glitch-free, zero-latency) --------------
   An <audio> element pays a real first-play init cost and can stutter on short
   one-shots — that was the cover-flip "lag/glitch". Instead we decode each SFX
   ONCE into an AudioBuffer and play it through a BufferSource: sample-accurate,
   no start latency. Any leading silence baked into the mp3 is auto-skipped (we
   start on the first audible sample). Buffers come from base64 data URIs
   (window.SFX_DATA in sfx-data.js) so they decode even on file://, where fetch()
   of a plain path is blocked. If Web Audio is unavailable we fall back to plain
   <audio> elements (the old behaviour). */
let audioCtx = null;
const sfxBuf = {};                          // name -> { buffer, offset (seconds) }

// Fallback <audio> elements — used ONLY if Web Audio fails to init or decode.
// Ogg/Opus: Chrome, Edge, Firefox, Safari 15+. preload="none" because these are
// rarely-needed fallbacks — the base64 Web Audio path (sfx-data.js) is the normal
// route, so there is no reason to spend a request on them up front.
const flipSound = new Audio("sfx/Page%20flip.ogg");
flipSound.preload = "none";
const coverFlipSound = new Audio("sfx/cover%20page%20flip.ogg");
coverFlipSound.preload = "none";
coverFlipSound.volume = 0.35;

(function initSfx() {
  const AC = window.AudioContext || window.webkitAudioContext;
  const DATA = window.SFX_DATA || {};
  if (!AC) return;                          // no Web Audio at all → <audio> fallbacks
  try { audioCtx = new AC(); } catch (_) { audioCtx = null; return; }
  // BACKGROUND-MUSIC GAIN — the ctx is created even if the inlined SFX data is
  // missing, because this route is what makes the idle/duck levels real on iOS
  // (see the bgLevel note above). Once the element is wired through the graph the
  // gain node OWNS the level, so the element volume must sit at 1 (never both —
  // that would double-attenuate on platforms where el.volume works).
  try {
    const bgSrc = audioCtx.createMediaElementSource(bgMusic);
    bgGain = audioCtx.createGain();
    bgGain.gain.value = bgLevel;
    bgSrc.connect(bgGain).connect(audioCtx.destination);
    bgMusic.volume = 1;
  } catch (_) { bgGain = null; }
  if (!DATA.cover) return;                  // no inlined SFX data → <audio> fallback for one-shots
  function decode(name, uri) {
    fetch(uri).then(function (r) { return r.arrayBuffer(); })
      .then(function (a) { return audioCtx.decodeAudioData(a); })
      .then(function (buf) {
        // Skip any leading silence so playback starts right on the transient.
        const ch = buf.getChannelData(0), sr = buf.sampleRate, thr = 0.008;
        let first = 0;
        for (let i = 0; i < ch.length; i++) { if (Math.abs(ch[i]) > thr) { first = i; break; } }
        sfxBuf[name] = { buffer: buf, offset: Math.max(0, first / sr - 0.004) };
      })
      .catch(function () {});               // leave name unset → falls back to <audio>
  }
  decode("cover", DATA.cover);
  decode("flip", DATA.flip);
})();

// The audio context starts suspended until a user gesture. Resume it on the first
// pointer press (fires just BEFORE the open click) so the cover-flip sound, played
// a moment later, is instant. Capture phase, not once (cheap + always safe).
function resumeAudio() {
  if (audioCtx && audioCtx.state === "suspended") { try { audioCtx.resume(); } catch (_) {} }
}
document.addEventListener("pointerdown", resumeAudio, { capture: true });

// Play a decoded SFX buffer; returns false if Web Audio isn't ready (→ caller
// falls back to the <audio> element).
function playSfx(name, vol, rate) {
  const entry = sfxBuf[name];
  if (!audioCtx || !entry) return false;
  try {
    if (audioCtx.state === "suspended") audioCtx.resume();
    const src = audioCtx.createBufferSource();
    src.buffer = entry.buffer;
    if (rate) src.playbackRate.value = rate;
    const g = audioCtx.createGain();
    g.gain.value = (vol == null ? 1 : vol);
    src.connect(g).connect(audioCtx.destination);
    src.start(0, entry.offset || 0);        // start on the first audible sample
    return true;
  } catch (_) { return false; }
}

// Page-flip sound — snappy 1.5× on every ordinary flip.
function playFlip() {
  if (muted) return;                        // sound turns on when the book opens
  if (playSfx("flip", 1.0, 1.5)) return;    // Web Audio path
  try {                                     // fallback
    flipSound.currentTime = 0; flipSound.playbackRate = 1.5;
    const p = flipSound.play(); if (p && p.catch) p.catch(function () {});
  } catch (_) {}
}
// COVER-page flip sound — played ONLY when the cover opens (never on page flips).
function playCoverFlip() {
  if (muted) return;
  if (playSfx("cover", 0.35)) return;       // Web Audio path
  try {                                     // fallback
    coverFlipSound.currentTime = 0;
    const p = coverFlipSound.play(); if (p && p.catch) p.catch(function () {});
  } catch (_) {}
}
// Turn sound ON when the book is opened (a clear user gesture). Safe to call
// repeatedly.
function soundOn() {
  muted = false;                     // opening the book turns sound on
}


/* ==========================================================================
   PAGE-TURN HINT  —  guidance for readers who don't know how to turn the page.
   When idle, two cues fire together: a hand taps the forward arrow AND the page
   itself does a "ghost" half-flip (lifts toward the next page, then falls back).
   Timing: PAGE 1 after 5s, every later page after 10s of no interaction; repeats
   while idle and is cancelled by any tap / key / flip. Never on the last page or
   while the LBD game is open.
   ========================================================================== */
// The nudge is a HAND on the RIGHT side of the book, drawn as an emoji glyph.
// (It previously tried assets/hand-nudge.png first and fell back to the emoji via an
// error handler — but that art was never shipped, so every load spent a guaranteed
// 404 to reach the same emoji. The <img> + error dance is gone; to use real art,
// swap this for an <img>, add the file to the `shell` list in tools/gen-manifest.js,
// and keep an error fallback.)
const flipHint = document.createElement("div");
flipHint.className = "flip-hint flip-hint--emoji";
flipHint.setAttribute("aria-hidden", "true");
flipHint.textContent = "👆";
document.body.appendChild(flipHint);

// Idle guidance timing: the FIRST nudge is after 5s on page 1, 10s on later pages;
// then it plays ONCE, disappears, and comes back every 9s. Any interaction resets it.
function idleDelay() { return flipped === 0 ? 5000 : 10000; }
const NUDGE_SHOW_MS = 2000;    // how long one nudge stays on screen
const NUDGE_GAP_MS  = 9000;    // gap after it disappears before it plays again
let idleHintTimer = null;
let nudgeHideTimer = null;
let videoEndHintTimer = null;    // 5s-after-video-ends → flip-page tutorial
let peeking = false;
let peekTimers = [];

function canShowHint() {
  return opened && ready && !animating && !lbdFullscreen &&
         flipped < totalPages - 1 && !isLbdPage(flipped) && !document.hidden;
}
function positionFlipHint() {
  if (!flipScaleEl) return;
  const r = flipScaleEl.getBoundingClientRect();            // the book's on-screen rect
  const w = flipHint.offsetWidth || 80, h = flipHint.offsetHeight || 80;
  // Park the hand against the book's RIGHT edge, vertically centred — the side the
  // ghost flip lifts. The swipe animation moves it right→left from here.
  flipHint.style.left = Math.round(r.right - w - r.width * 0.05) + "px";
  flipHint.style.top  = Math.round(r.top + r.height * 0.5 - h / 2) + "px";
}
function showFlipHint() {
  if (!canShowHint()) return;
  positionFlipHint();
  flipHint.classList.add("show");
}
function hideFlipHint() {
  flipHint.classList.remove("show");
}

/* ---- GHOST PAGE-FLIP -------------------------------------------------------
   Lift the current page about halfway toward the next one, then let it fall back
   — a live demo that the page turns. Purely visual; cancelled the instant the
   reader interacts, so a real drag/flip takes over cleanly. */
function cancelPeek() {
  peekTimers.forEach(clearTimeout);
  peekTimers = [];
  if (!peeking) return;
  peeking = false;
  const leaf = leaves[flipped];
  if (leaf) {
    leaf.style.transition = ""; leaf.style.transform = ""; leaf.style.zIndex = "";
    const c = leaf.querySelector(".curl"); if (c) c.style.opacity = "";
  }
  updateZ();
}
function peekFlip() {
  if (peeking || !canShowHint()) return;
  const leaf = leaves[flipped];
  if (!leaf) return;
  peeking = true;
  const curl = leaf.querySelector(".curl");
  leaf.style.zIndex = 300;                               // lift above the rest while peeking
  leaf.style.transition = "transform 720ms cubic-bezier(0.33, 0, 0.2, 1)";
  void leaf.offsetWidth;                                 // commit so the lift animates from flat
  leaf.style.transform = "rotateY(-52deg)";              // turn toward the next page (~halfway)
  if (curl) curl.style.opacity = "0.85";                 // page-curl shading during the lift
  peekTimers.push(setTimeout(function () {               // ...then ease it back down
    leaf.style.transform = "rotateY(0deg)";
    if (curl) curl.style.opacity = "";
  }, 760));
  peekTimers.push(setTimeout(function () {               // clean up once settled
    leaf.style.transition = ""; leaf.style.transform = ""; leaf.style.zIndex = "";
    peeking = false; updateZ();
  }, 760 + 760));
}

// Play the nudge ONCE — hand swipe on the book's right + ghost page-flip + the
// right arrow blinks — hold ~2s, then hide and come back 9s later. Repeats while idle.
function triggerHint() {
  if (!canShowHint()) { idleHintTimer = setTimeout(triggerHint, NUDGE_GAP_MS); return; }
  showFlipHint();
  peekFlip();
  if (cornerNext) cornerNext.classList.add("blink");
  clearTimeout(nudgeHideTimer);
  nudgeHideTimer = setTimeout(function () {
    hideFlipHint();
    if (cornerNext) cornerNext.classList.remove("blink");
    idleHintTimer = setTimeout(triggerHint, NUDGE_GAP_MS);   // ...then again after 9s
  }, NUDGE_SHOW_MS);
}
// FLIP-PAGE TUTORIAL — called when a page's video ENDS. Waits 5s, then starts
// the page-turn guidance (hand swipe + ghost flip + blinking arrow), which then
// repeats every ~9s (via triggerHint) until the reader flips. Cleared by any
// interaction / page change (see resetIdleHint).
const VIDEO_END_TUTORIAL_MS = 5000;
function scheduleVideoEndTutorial() {
  clearTimeout(videoEndHintTimer);
  videoEndHintTimer = setTimeout(function () {
    if (!canShowHint()) return;
    clearTimeout(idleHintTimer);   // take over from any idle loop so they don't stack
    triggerHint();                 // hand + ghost flip + arrow blink, self-repeats
  }, VIDEO_END_TUTORIAL_MS);
}
function currentIsVideoPage() {
  return !!(pages[flipped] && pages[flipped].type === "video");
}
function resetIdleHint() {
  hideFlipHint();
  cancelPeek();
  if (cornerNext) cornerNext.classList.remove("blink");
  clearTimeout(idleHintTimer);
  clearTimeout(nudgeHideTimer);
  clearTimeout(videoEndHintTimer);
  // On a VIDEO page the flip tutorial is driven by the video-end + 5s handler
  // (scheduleVideoEndTutorial), so we DON'T run the generic idle countdown — the
  // hint appears only once the video has actually finished. On non-video pages
  // (e.g. an image), fall back to the normal idle countdown.
  if (!currentIsVideoPage()) {
    idleHintTimer = setTimeout(triggerHint, idleDelay());     // first show: 5s (pg1) / 10s (later)
  }
}
// Any interaction cancels the nudge + restarts the idle countdown.
["pointerdown", "keydown", "wheel", "touchstart"].forEach(function (evt) {
  document.addEventListener(evt, resetIdleHint, { passive: true, capture: true });
});

/* ---- Boot ---------------------------------------------------------------- */
fitScale();                              // scale the fixed 1280x720 book to fit first
renderLeaves();                          // lay out the leaves (all on page 1 to start)
updateNavControls();                     // controls stay hidden until the book opens

/* STAGE B — starts only AFTER the flipbook's own load event, during idle time, so it
   can never compete with Stage A or delay the Start button:
     • preload.js warms the remaining bytes (later videos, both games' assets);
     • warmLbd() boots the upcoming game into the hidden iframe so landing on its
       page shows a live intro instantly, with no spinner and no second loading screen.
   Both games are silent until their own Play button is tapped, so booting one hidden
   leaks no audio. */
window.addEventListener("load", function () {
  if (window.FlipbookPreload) window.FlipbookPreload.startStageB();
  // Give Stage B's prioritised queue (theme music, then the story videos in page order)
  // a short head start before booting the game. LBD 1's own audio.init() creates ~21
  // Audio objects with preload="auto", so booting it the same instant would put its
  // whole VO pack in front of the clip that plays on page 1. The learner cannot reach
  // a game page in under ~2 minutes of story video, so this costs nothing.
  setTimeout(warmLbd, 2000);
});

/* Public integration surface. Deliberately minimal: it exposes no way to skip a
   level, jump a page or bypass a gate — markInteractionComplete() is how a page's
   required activity reports SUCCESS, and the rest is read-only state. */
window.Flipbook = {
  /* The page config, so a page's own activity script can read its own entry (and so
     the gating suite can exercise the `interactive` requirement). Exposing this grants
     nothing: it can only ADD a requirement, never satisfy or skip one. */
  pages: pages,
  markInteractionComplete: markInteractionComplete,
  canNavigateForward: canNavigateForward,
  goNext: function () { goNext(); },      // gated — never the internal bypass
  goPrev: goPrev,
  gateState: function () {
    return {
      page: flipped,
      totalPages: totalPages,
      armedFor: gateArmedIdx,
      videoCompleted: firstPageVideoCompleted,
      interactionCompleted: firstPageInteractionCompleted,
      hasVideo: pageHasVideo(flipped),
      hasInteraction: pageHasInteraction(flipped),
      canForward: canNavigateForward(),
      cleared: Array.from(clearedPages).sort(function (a, b) { return a - b; }),
      nextHiddenWhileLocked: nextArrowHiddenWhileLocked(flipped),
      lbdFullscreen: lbdFullscreen,
      lbdStarted: lbdStarted,
      lbdLoaded: lbdFrame ? (lbdFrame.dataset.loaded || "") : "",
      lbdReadySrc: lbdReadySrc,
      overlayVisible: !!(lbdOverlay && lbdOverlay.classList.contains("visible")),
      opened: opened,
      ready: ready,
      animating: animating,
    };
  },
  /* Test-only affordance for the gating suite: re-arms the current page's gate after
     a page's `interactive` flag is changed. Cannot unlock anything on its own. */
  rearmGate: function () { armForwardGate(flipped); },
};
